# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Highlights"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "//hugo.schman.at/themes/highlights"
tags = ["portfolio", "onepage", "one page", "contact form", "google analytics"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Manuel Schneider"
  homepage = "//schman.at/hugo"

# If porting an existing theme
[original]
  name = "HTML5UP - Highlights"
  homepage = "//html5up.net/highlights"
  repo = ""
